### ISSUE TITLE
[Regression] Application Name and Default Namespace are empty 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1150] opened 2017-01-12 19:24 UTC
- Create console application 
- Right click properties 
- Select Application Tab 

**Expected** 
![image](https://cloud.githubusercontent.com/assets/12449387/21904758/99400952-d8b9-11e6-972a-3f62d5a2cd35.png)

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/21904656/4fd2cd0e-d8b9-11e6-9858-092bae02ddac.png)

Works in 26110.0.d15rel
Fails in  26111.0.d15rel

**Comment by srivatsn** [comment] 2017-01-12 19:36
Dupe of https://github.com/dotnet/roslyn-project-system/issues/1135 @basoundr

**Closed by srivatsn** 2017-01-12 19:36 UTC

**Comment by jinujoseph** [comment] 2017-01-12 21:52
@srivatsn this is different from 1135

**Comment by rainersigwald** [comment] 2017-01-13 23:06
This also seems to be https://github.com/Microsoft/msbuild/issues/1570 so I think it really was a duplicate (not entirely sure _how_ but there it is).
