### ISSUE TITLE
Resources page throwing error

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#441] opened 2016-09-02 21:31 UTC
![image](https://cloud.githubusercontent.com/assets/10550513/18218760/de31b7c0-7119-11e6-8d46-f7024bc4e7af.png)

Thought this was fixed earlier.

Project is a Console Application

**Comment by srivatsn** [comment] 2016-09-02 21:33
Dupe of https://github.com/dotnet/roslyn-project-system/issues/419

**Closed by srivatsn** 2016-09-02 21:33 UTC
Labels: Bug
