### ISSUE TITLE
Project System: Simplified Add Item

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#77] opened 2016-05-13 05:26 UTC
_From @davkean on March 22, 2016 23:58_

This is tracking simplified add item - ie choose Add Item, such as Add Windows Form, should add to the tree and automatically enter rename mode instead of opening the dialog.

_Copied from original issue: dotnet/roslyn#9998_

**Comment by NoneGiven** [comment] 2016-05-19 16:57
Dupe of #136

**Closed** 2016-05-19 16:59 UTC
Labels: 0 - Backlog, Feature Request, New Feature
