### ISSUE TITLE
"Unrecognized Guid Format" when trying to add a class through solution explorer

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#438] opened 2016-09-02 21:07 UTC
![image](https://cloud.githubusercontent.com/assets/10550513/18218261/572a021c-7116-11e6-8e63-8c19210753cf.png)

I see that there was already an issue opened #392 but fixed.

Installed 25702.00 wpt build and 20160902-1 drop of core sdk

**Comment by 333fred** [comment] 2016-09-02 21:14
Closing as a duplicate of #392

**Closed by 333fred** 2016-09-02 21:14 UTC
Labels: Bug
