### ISSUE TITLE
P2P Reference from old .Net framework class Library to new .Net Standard Class Library Not working 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#720] opened 2016-11-07 19:30 UTC
**Repro Steps**

- Create a .Net Framework Class Library (old csproj) [4.5.2]
- Create  a .Net standard Class Library (new .net core)  [ netstandard1.2]
- Add reference from .Net Framework  to .Net standard Class Library
- Build

**Expected**
Build Succeeded

**Actual**
Build Failed
image
![image](https://cloud.githubusercontent.com/assets/12449387/20072488/7eee547e-a4dd-11e6-8cd4-0554b57278da.png)

![image](https://cloud.githubusercontent.com/assets/12449387/20072548/b1c39c1a-a4dd-11e6-9286-c4d6832d9f10.png)

Enviornment Info

build: d15rel/25904.2
cli: 1.0.0-preview3-004056

**Comment by srivatsn** [comment] 2016-11-07 21:16
Is that a build failure or do you just see that in the error list? Old csproj issues this error at design time afaik.

**Comment by jinujoseph** [comment] 2016-11-07 21:17
i get an error when i try to call a method in standardCL , else it compiles fine

**Comment by srivatsn** [comment] 2016-11-21 21:03
Dupe of https://github.com/dotnet/sdk/issues/266

**Closed by srivatsn** 2016-11-21 21:03 UTC
Labels: Bug
