### ISSUE TITLE
Can't add a reference from legacy csporj -> to a project that hasn't been restored

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#597] opened 2016-10-13 00:58 UTC
1. Create desktop legacy project system project
2. Create .NET Core project system project
3. Attempt to add a reference from desktop -> .NET Core

![image](https://cloud.githubusercontent.com/assets/1103906/19332918/89100142-90a5-11e6-818e-6639245d8c84.png)

**Comment by adrianvmsft** [comment] 2016-10-17 17:13
Looks like this issue has the same root cause as #581
If you insert the target into the project, you can add the project reference just fine.

**Comment by basoundr** [comment] 2016-11-02 20:42
Fixed in #664. Verified in d15rel 25831.0

**Closed by basoundr** 2016-11-02 20:43 UTC
Labels: Bug
