### ISSUE TITLE
Adding Resource file to Console Application results in error

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#443] opened 2016-09-02 22:08 UTC
![image](https://cloud.githubusercontent.com/assets/10550513/18219488/df4d3e36-711e-11e6-96ff-975b9ca4883a.png)

As you can see in the image that designer throws an error and the solution explorer does not realize that the .designer.cs is supporting file for .resx file

VS - wpt branch - 25702.00

**Comment by davkean** [comment] 2016-09-02 22:24
Dupe of https://github.com/dotnet/roslyn-project-system/issues/419

**Closed by davkean** 2016-09-02 22:24 UTC
Labels: Bug
