### ISSUE TITLE
Properties of a project reference don't have defaults set

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#593] opened 2016-10-12 20:00 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/19325612/cfa4475a-907b-11e6-974f-9371ed2216ef.png)

Expected that the non-read only properties have their defaults sets.

**Comment by abpiskunov** [comment] 2017-01-07 03:49
this is a dupe of #59 , closing it

**Closed by abpiskunov** 2017-01-07 03:49 UTC
Labels: Bug
