### ISSUE TITLE
VS project.json migration shouldn't delete global.json before calling `dotnet migrate`

### ISSUE THREAD

**Issue by eerhardt** [dotnet/roslyn-project-system#1376] opened 2017-01-30 17:46 UTC
See https://twitter.com/blaken/status/824827246091309057

Repro steps:
1. git clone https://github.com/exceptionless/foundatio
2. Open the .sln file in VS 2017 RC3
3. Migrate the project.json based projects to .csproj.

### Expected Results
The migration should succeed.

### Actual Results
[UpgradeLog.htm.txt](https://github.com/dotnet/roslyn-project-system/files/739756/UpgradeLog.htm.txt)

All the "test" and "sample" projects fail to migrate.

### Notes
I believe this is because VS deletes the `global.json` file before calling `dotent migrate`.  See https://github.com/dotnet/roslyn-project-system/blob/ea445f5cd6e567196c285e4f254695858158165b/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs#L55.  

This is an issue because `dotnet migrate` needs the `projects` section of the `global.json` file in order to resolve P2P references across directories - which is what is happening here.  There are P2P references from the "test" directory to the "src" directory.

/cc @livarcocc

**Comment by 333fred** [comment] 2017-01-30 18:10
This was designed to work this way: https://github.com/dotnet/roslyn-project-system/issues/1184. The issue is if there's a global.json that specified a lower version of the cli, it probably won't call the correct version of dotnet migrate.

**Comment by livarcocc** [comment] 2017-01-30 18:11
@333fred I wonder if we are hitting the issue fixed by https://github.com/dotnet/cli/pull/5352. When I talked to @eerhardt, his version of the CLI was older and did not have that fix in.

**Comment by livarcocc** [comment] 2017-01-30 18:11
@333fred I believe we should try this scenario in a VS instance that definitely has a newer version of the CLI.

**Comment by 333fred** [comment] 2017-01-30 18:12
I'll update to the latest d15prerel and try locally.

**Comment by 333fred** [comment] 2017-01-30 18:24
@livarcocc no dice, failed with `test\Foundatio.Benchmarks\Foundatio.Benchmarks.xproj: MIGRATE1014::Unresolved Dependency: Unresolved project dependency (Foundatio)` on ~1/2 of projects. CLI version:
```
C:\Users\frsilb>dotnet --info
.NET Command Line Tools (1.0.0-rc4-004689)

Product Information:
 Version:            1.0.0-rc4-004689
 Commit SHA-1 hash:  c740fa8f43

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004689
```

**Comment by livarcocc** [comment] 2017-01-30 18:52
All right. I will take a look.

**Comment by eerhardt** [comment] 2017-01-30 19:10
> This was designed to work this way: #1184. The issue is if there's a global.json that specified a lower version of the cli, it probably won't call the correct version of dotnet migrate.

Agreed having the old "sdk" version is a problem.  A solution may be to delete the "sdk" property out of the global.json instead of removing the whole thing.

**Comment by livarcocc** [comment] 2017-01-30 20:10
I think @eerhardt is right after all. As usual! I don't see how this scenario ever worked. When we try to migrate a project under test/project, we only search for dependencies under the test folder, because there is nothing telling us to search for projects under src/ (that would be in the projects of the global.json).

Now, we could do a fix in the CLI to not validate these projects, but the problem here would be that we could end up migrating project dependencies as package dependencies. Only references marked with target: project would be migrated as project, the other ones, because we didn't find them, would migrate as package references.

@333fred How feasible would it be to only move the global.json at the end of the process? A problem because of the SDK property? Otherwise, I don't see how migration can get this right for all cases.

**Comment by 333fred** [comment] 2017-01-30 20:26
@livarcocc and I talked offline. I'll prep a change that will remove the sdk element from the global.json and delete the global.json after migration is completed.

**Closed** 2017-01-31 22:41 UTC
Labels: Bug, RC3 Known Issue
