### ISSUE TITLE
Analyzers aren't listed for customization in Solution Explorer

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-project-system#1294] opened 2017-01-21 16:27 UTC
Using: d15prerel 26119.00

1. Create a netstandard library in VS
1. Install stylecop.analyzers nuget package
1. Examine the stylecop.analyzers node in Solution Explorer

**Expected**
The node to be expandable so I can see all individual analyzers and control whether each one produces errors, warnings, info, etc.

**Actual**
No analyzers listed:

![image](https://cloud.githubusercontent.com/assets/3548/22175897/7af59e7a-dfb3-11e6-8a75-8ff8ff85551b.png)

**Comment by abpiskunov** [comment] 2017-01-25 20:56
It is by design that we show only dependencies in package hierarchy, not content or other info inferred by package content. So this is a feature request.  There should be a separate Analyzers Sub node under Dependencies at the moment which should display all analyzers in the project. However i suppose it only shows explicit project items like AnalyzerRefernce , not other analyzers that can be discovered form packages. 

@srivatsn  lets brainstorm what would be ideal solution here for U1.

**Comment by AArnott** [comment] 2017-01-25 23:35
This is a take back from project.json dependencies that carry analyzers.

**Comment by abpiskunov** [comment] 2017-01-26 00:02
yes , but package carries dlls , that in turn carry analyzers , it's different level a little... However i don't mind to show them there  if everyone agrees and sdk targets would provide data.

**Comment by srivatsn** [comment] 2017-01-26 00:07
We do want to show the individual rules in the project tree. It's tracked by https://github.com/dotnet/roslyn-project-system/issues/88. However we are unlikely to get to it for RTM. 

@AArnott why do you say it's a take-back? xproj project.json never had it (in fact analyzers didn't even work in the IDE) and UWP-style project.json will continue to work even if you convert to PackageReference because non-.NET Core projects will continue to use the old project system where this still works.

**Comment by AArnott** [comment] 2017-01-26 03:17
I wasn't referring to xproj. I was talking about c# portable class libraries that used project.json. When I port them to .net core projects I lose analyzers which is a big deal because it's the only convenient way to adjust their severity. 
Not a ship stopper, I agree. But I'm looking forward to the delivery of this feature ASAP.

**Comment by srivatsn** [comment] 2017-01-30 17:29
Me too. Closing this in favour of tracking it with #88

**Closed by srivatsn** 2017-01-30 17:29 UTC
