### ISSUE TITLE
Remove tabs from Reference Manager dialog that are not applicable to .NET Core

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#611] opened 2016-10-14 22:25 UTC
**INSTALL STEPS**
1. Install WPT.25813.01
2. Add private MyGet feeds in Package Manager Settings dialog

**REPRO STEPS**
1. File > New > Console Application (.NET Core)
2. Add > New Project > Class Library (.NET Standard)

**ACTUAL**
Reference manager defaults to the Framework tab

![image](https://cloud.githubusercontent.com/assets/8246794/19404343/2944882c-9222-11e6-8ca0-cc8c88a989cb.png)

**EXPECTED**
Remove Framework, Extensions and maybe COM tabs for .NET Core projects

**Comment by davkean** [comment] 2016-10-14 22:42
Thanks, keep these coming!

Dupe of https://github.com/dotnet/roslyn-project-system/issues/399 and https://github.com/dotnet/roslyn-project-system/issues/400.

**Closed by davkean** 2016-10-14 22:42 UTC
