### ISSUE TITLE
Editing .csproj of a project referenced by other projects causes a reload prompt.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#926] opened 2016-12-13 01:15 UTC
I have a repro here: https://github.com/MiniProfiler/dotnet/commit/0322808bfa20163d03c3a7181db666ede6e8be7f

When editing the `MiniProfiler.Shared` project, a reload prompt is caused when saving *any* changes (whitespace included):

<img width="711" alt="screen shot 2016-12-12 at 20 07 32" src="https://cloud.githubusercontent.com/assets/454813/21123508/254447b8-c0a7-11e6-83ea-7d92aca67715.png">

### Steps to repro
1. Right click `MiniProfiler.Shared`
2. Click `Edit MiniProfiler.Shared.csproj`
3. Add a space anywhere valid
4. Save

### Expected
File saves, no prompt

### Actual
File saves, and user is prompted to reload external changes or discard.

### Related
Some bonus issues I noticed with this, all related, not sure if know...happy to file them separately if new:
1. VS seems to semi-randomly append `<ItemGroup />` and `<PropertyGroup />` elements to the end of the `<Project>` section (noticed [in this commit](https://github.com/MiniProfiler/dotnet/commit/0322808bfa20163d03c3a7181db666ede6e8be7f#diff-c44d5e7bd1f44fa4835369183d6317bfR50)).
2. Opening 2 instances of VS creates quite a battle with file saves and reloads.
3. If you click discard changes when 2 VS instances are fighting over the project file, this happens:

<img width="1176" alt="screen shot 2016-12-12 at 20 12 55" src="https://cloud.githubusercontent.com/assets/454813/21123569/77afb96a-c0a7-11e6-8a05-1a063f959938.png">

**Comment by davkean** [comment] 2016-12-13 01:18
tag @333fred, can you take a look when you get a chance?

**Comment by 333fred** [comment] 2016-12-13 01:27
I'm not seeing the unsaved changes prompt locally, but I am seeing it write out a new project file a _lot_ of times. That part is probably caused by #738.

For the save/reload battles, that should be reduced by fixing #738 and moving to an in-memory edit model instead of temp-file based. I don't think it can ever fully go away though: if you have two different VS instances open and both have unsaved changes, they will battle each other when trying to save.

**Comment by 333fred** [comment] 2017-01-06 19:00
@NickCraver, the frequency of these prompts should be significantly reduced by #1027, and you shouldn't see a prompt on file save anymore after the next release. Please reopen if you continue to see issues.

**Closed by 333fred** 2017-01-06 19:00 UTC
Labels: Bug, Feature - Project File Editing
