### ISSUE TITLE
No XML documentation file in publish folder

### ISSUE THREAD

**Issue by deastr** [dotnet/roslyn-project-system#1603] opened 2017-02-23 07:22 UTC
I have checked XML documentation option in project settings. The XML file is in output folder but not in publish folder.

Using VS.NET 2017 RC4.

```
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by srivatsn** [comment] 2017-02-23 07:54
Dupe of https://github.com/dotnet/sdk/issues/795

**Closed by srivatsn** 2017-02-23 07:54 UTC
