### ISSUE TITLE
Should not show compiler errors until after the first restore

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1695] opened 2017-03-08 08:55 UTC
1. File -> New -> Web Application (.NET Core)

--Notice that there's errors in Startup.cs, which go away after restore--

We should stop reporting errors until after the first restore and we've got something useful. Thousands of errors about types that don;t exist yet because we've not restored is not helpful.

**Comment by srivatsn** [comment] 2017-03-23 19:01
Dupe of https://github.com/dotnet/roslyn-project-system/issues/928

**Closed by srivatsn** 2017-03-23 19:01 UTC
Labels: Feature Request
