### ISSUE TITLE
Context menu items for NuGet and Projects nodes in solution explorer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#449] opened 2016-09-02 23:38 UTC
![contextmenu](https://cloud.githubusercontent.com/assets/10605811/18220894/624cdbf0-712b-11e6-8e21-ccf5f2ab8593.png)

1. View in object browser is a no-op
2. Add Fakes Assembly throws "Language not supported" dialog
3. Properties window is empty

**Comment by abpiskunov** [comment] 2016-09-02 23:46
what is exactly you asking in this issue? To not show Properties menu item for root sub trees like Projects, Assemblies etc ?

**Comment by mavasani** [comment] 2016-09-02 23:49
I am not sure what needs to show up here, but the existing commands seem to be non-useful - if nothing relevant is applicable for the nodes, then I am fine with even having no context menu.

**Comment by abpiskunov** [comment] 2016-09-02 23:50
yes, sounds good

**Comment by srivatsn** [comment] 2016-10-21 07:41
Dupe of #398

**Closed by srivatsn** 2016-10-21 07:41 UTC
Labels: Bug
