### ISSUE TITLE
Adding/removing a Shared Project does not update the dependency node

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#954] opened 2016-12-15 00:30 UTC
Repro steps:
1) Create a new .Net Core console app
2) Add a shared project to the solution
3) Right click on the console app and "Add Reference"
4) Select the shared project and press Ok

Expected: Dependency node is update
Actual: Dependency node is not updated.

**Comment by basoundr** [comment] 2017-01-13 22:01
Some of the things mentioned here have started working. The reference is indeed added because we now have intellisense over the shared project types. 

Only the dependency node is not working. If you close and open the solution, dependency node works too.

Moving it over to Anton

**Comment by abpiskunov** [comment] 2017-01-13 22:20
While i am offline, could you please check if DT build event is sent to dependencies tree provider after you added project reference?

Thanks,
Anton

On Jan 13, 2017, at 12:01 PM, Balaji Soundrarajan <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #954<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Froslyn-project-system%2Fissues%2F954&data=02%7C01%7Canton.piskunov%40microsoft.com%7C5ab8dcf277354522b86908d43bffbcf3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636199416952042621&sdata=70RYI5DfcIz9de9ZaZDJvsobt9DVrZtaKAwnzsiwgYE%3D&reserved=0> to @abpiskunov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabpiskunov&data=02%7C01%7Canton.piskunov%40microsoft.com%7C5ab8dcf277354522b86908d43bffbcf3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636199416952042621&sdata=ENQRsFRJKDxsQNSBFnc5OGj27jBfg4Stj%2FYgk2KD5nw%3D&reserved=0>.

-

**Comment by abpiskunov** [comment] 2017-01-13 23:28
Then it should not be under dependencies tree, but either in CPS or Sdk.

Thanks,
Anton

On Jan 13, 2017, at 12:51 PM, Balaji Soundrarajan <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried a break point at OnDependenciesChanged<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Froslyn-project-system%2Fblob%2Fmaster%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Managed.VS%2FProjectSystem%2FVS%2FTree%2FDependencies%2FDependenciesProjectTreeProvider.cs%23L330&data=02%7C01%7Canton.piskunov%40microsoft.com%7C3df1d8872f4b4cdca90d08d43c06ad2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636199446758353646&sdata=oV0BISYmayWn2ucbwZdMvWcjOUQMp2mCeKsCI2Gwxvs%3D&reserved=0> and it did not get hit when the reference was added/removed

-

**Comment by davkean** [comment] 2017-01-20 02:30
@srivatsn Picking this up to find an owner.

**Comment by davkean** [comment] 2017-01-20 03:24
I debugged through this, this doesn't appear to be a CPS issue. CPS is firing the data flow events from the SharedFoldersSource block (and gives me the right data if I manually listen). It appears to be related to the way that also linking to the evaluation + project catalog + shared folders:

``` C#
                 _projectSyncLinks.Add(ProjectDataSources.SyncLinkTo(
                                intermediateBlockEvaluation.SyncLinkOptions(),
                                ProjectSubscriptionService.ProjectCatalogSource.SourceBlock.SyncLinkOptions(),
                                ProjectSubscriptionService.SharedFoldersSource.SourceBlock.SyncLinkOptions(),
                                actionBlock));
```

Perhaps updates are being held back until these versions are in sync?

**Comment by davkean** [comment] 2017-01-20 03:41
I suppose I don't understand the expectation here @lifengl and @abpiskunov?

**Comment by davkean** [comment] 2017-01-24 05:18
Assigning back to @abpiskunov, can you please help me understand the expectation here?

**Comment by abpiskunov** [comment] 2017-01-24 20:06
@davkean  expectation here is that we receive an event when shared project is added to our csproj. We do subscribe to the event from ProjectSubscriptionService.SharedFoldersSource.SourceBlock.SyncLinkOptions() and we do receive events when shared project is loading (or added to solution) so links are working and events are firing in general. 
I tried to comment second subscription that you mentioned, that connects to evaluation, still no events are sent to me when i add shared project. My subscription is the same that References nodes provider has in CPS, so i assume it did work. Also notice: even though shared project added to csproj, when i open Add Reference dialog again , it does not have it's checkbox checked. Can that be related somehow?
I think at this point we need to ask Lifeng to look at it to see what happens to the event.

**Comment by davkean** [comment] 2017-01-24 21:22
@abpiskunov As mentioned, I manually added a subscription that is not linked to any other block and the correct data is sent through. As soon as it's linked to the other sources, it's no longer sent.

I just repro'd the same issue with the Reference Manager, but if I unload the project and reload it, then the Shared Project was added. I don't know how the Reference Manager is populated.

@lifengl can you add some guidance here?

**Comment by lifengl** [comment] 2017-01-28 01:56
It is a bug in the dependency tree data flow code.  I read the code, and it is using suppressVersionOnly change in couple places.  You should prevent using that flag, expect might be the final link to an action block.  Using it in the middle of a data flow can easily introduce a problem like that or a dead lock.

The entire CPS data flow depends on the data source version to flow through the entire data flow blocks. It is important so the system can detect whether there is any pending change not being processed through the entire system.  To do that, a version only change must be passed to the next dataflow block, even the internal data has no change, and each block is responsible to update the version number of its output based on the data source version of all its input.  When the input version is changed, even the data is not changed, it need publish a new piece of data carrying a new version number.

Based on this, the system can check the current output of a data flow to know whether it is up to date, or there are still something going in the background, so it hasn't receive the latest data.  For example, if the project is changed, its version number will increase, we can monitor the version number from the project tree to see whether it is representing the project after this change.  So, even the change is touching some property, which does not affect the project tree, it need publish a new tree (even no change) with the updated version number.  Otherwise, some code waiting on that will wait for ever, and will cause a dead lock.

Now, thinking about you have multiple dataflow block to process the project data, and you take all of them as your input.  The problem is that the data publishing from those blocks might be mismatching.  Some of them might come from the earlier state of the project, and some of them come from the later state.  If you work with that data, you might run into some problems because the data coming from different sources are mismatching.  Or maybe your code can deal with that, but consider a new change of the project will be published from all 3 source blocks as your input, you will receive notification 3 times, and publish 3 times based on mismatching data.  To prevent that, the SyncLink is to match the version number of those input blocks, and eliminates input data, when they come from different version of the project, and only publish the data to the next level, when all data are matching with each other.  This will reduce lots of extra processing.  Now, when you put a dataflow block suppressing version only change in one of the source block, you can see it will cause a problem.  If the change doesn't impact the output of this block, it doesn't publish anything, so the syncLink block will not get a set of consistent input, and nothing will be pushed to the next level.  The entire system will be on the floor.

That is exactly what the dependency tree code did today.  It suppressed version only change in some middle level blocks.  I think you should get rid of them, and make sure you always publish a new version of the dependency tree after every version change.

**Comment by davkean** [comment] 2017-01-30 06:47
Assigning back to @abpiskunov, as per @lifengl's comment.

**Closed** 2017-02-01 22:49 UTC
Labels: Bug, Urgency-Soon
