### ISSUE TITLE
New files added to a cross compiled project do not get compiled for all TFMs

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn-project-system#1769] opened 2017-03-16 17:44 UTC
Repro steps:

1. Create a new class library project. Edit the csproj to cross-compile it for more than one tfm. e.g. `<TargetFrameworks>net451;netstandard1.3</TargetFrameworks>`
2. VS will prompt to reload the project. Reload it.
3. Add a new class to the project.

Expected:
The new type is compiled for both the specified TFMs.

Actual:
The new type is compiled for only one of the two TFMs. You have to reload the project \ solution to get it to work correctly:

![image](https://cloud.githubusercontent.com/assets/174281/24010541/73ceb3fa-0a35-11e7-8ddd-0abdd3f60357.png)

**Comment by davkean** [comment] 2017-03-16 21:04
@mavasani This is the same bug as the one you fixed right?

**Comment by mavasani** [comment] 2017-03-16 21:06
Yes, can you try to repro it with latest bits? I think the fix did not meet the bar for 15.1

**Comment by pranavkm** [comment] 2017-03-16 21:12
Is this the latest d15 bits?

**Comment by mavasani** [comment] 2017-03-16 21:14
The fix did not make it into d15. I meant to ask @davkean to verify if this repros with latest ProjectSystem bits.

**Comment by davkean** [comment] 2017-03-16 23:47
This is a dupe of https://github.com/dotnet/roslyn-project-system/issues/1612

**Closed by davkean** 2017-03-16 23:47 UTC
