### ISSUE TITLE
Referencing .NET Standard Class Libraries (new project system) from a Classic .NET Class Library (old project system)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#783] opened 2016-11-21 05:43 UTC
One of the value props of a .NET Standard Class Library is that it can be referenced from any other project with a compatible target framework. Seems like that isn't the case with the new project system. Something is blocking it.

ClassLibrary1 = .NET Framework 4.6 Class Library 
ClassLibrary3 = .NET Standard Class Library

![image](https://cloud.githubusercontent.com/assets/95136/20471821/9a58648e-af69-11e6-84c1-a181d107a3cb.png)

However, if you reference a .NET Standard Class Library using the older project system, it works fine:

ClassLibrary2 = .NET Portable Class Library converted to .NET Standard:

![image](https://cloud.githubusercontent.com/assets/95136/20471927/52093f36-af6a-11e6-8aa5-d5c897448b6b.png)

![image](https://cloud.githubusercontent.com/assets/95136/20471907/209ff160-af6a-11e6-87e4-245459fc1ee7.png)

**Comment by dsplaisted** [comment] 2016-11-21 06:41
This is also tracked by dotnet/sdk#266.  In reality the bug is neither in the SDK or in the Roslyn Project system, but in some native code inside Visual Studio.  There's code there that tries to validate whether you can reference a project and generally they need to have the same target framework identifier.

The reason it works when you reference a "PCL-style" .NET Standard project is that the TargetFrameworkIdentifier in that case is still set to .NETPortable, and that's one of the exceptions in the code that checks whether you can reference something.  We need to add ".NETStandard" as an exception too.

**Comment by davidfowl** [comment] 2016-11-21 09:06
Yea, but it needs to work when they are compatible regardless of old/new project system. We might have to either put more stuff in the project file or in the targets file to make this work (I assume). Or change the native code in VS.

**Comment by dsplaisted** [comment] 2016-11-21 14:06
Yes, it needs to be fixed, we are planning to change the native code in the old project system.

**Comment by srivatsn** [comment] 2016-11-21 19:58
Dupe of https://github.com/dotnet/sdk/issues/266

**Closed by srivatsn** 2016-11-21 19:58 UTC

**Comment by davidfowl** [comment] 2016-11-29 11:16
@srivatsn why is the bug in the SDK? Isn't it a project system bug?

**Comment by srivatsn** [comment] 2016-11-29 21:13
It's actually a native project system bug. So the fix is in internal devdiv repo and is going in today.
