### ISSUE TITLE
Find in Solution doesn't search in .csproj files

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn-project-system#1292] opened 2017-01-21 02:37 UTC
Repro:

 - Create .NET Core App
 - Use VS search to search for "SDK" in the Solution
![image](https://cloud.githubusercontent.com/assets/41759/22171297/82b08dd8-df3f-11e6-8d1f-7fe975d853c2.png)

Expected:
SDK is found in .csproj file

Actual:
No matches found.

**Comment by davkean** [comment] 2017-01-23 00:24
Dupe of https://github.com/dotnet/roslyn-project-system/issues/35.

This occurs when the project is open - they can't open open the project file, so they don't show the results.  Given we now open the project file while the project is open, we should be able to do this soon.

**Closed by davkean** 2017-01-23 00:24 UTC

**Comment by davkean** [comment] 2018-05-28 14:41
Microsofties, this PR is fixing this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124985?_a=overview.

**Comment by davkean** [comment] 2018-11-15 07:04
This has been fixed in recent builds.
