### ISSUE TITLE
Settings property page should not show up for .NET Core projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#418] opened 2016-08-30 21:31 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/18107792/4688d29e-6ebe-11e6-8181-7c9c90284a04.png)

The APIs do not existing in .NET Core - we should drive this off a capability.

**Comment by srivatsn** [comment] 2016-11-10 07:16
Dupe of #572

**Closed by srivatsn** 2016-11-10 07:16 UTC
Labels: Bug
