### ISSUE TITLE
Typo while editing csproj crashes/hangs Visual Studio

### ISSUE THREAD

**Issue by codito** [dotnet/roslyn-project-system#1541] opened 2017-02-13 12:26 UTC
## Repro Steps
1. Create a new .netcore class library
2. Right click project on solution explorer, Edit csproj
3. Add following text in `PropertyGroups`
```
<DebugType Condition="'$(TargetFramework)' != '' AND $(TargetFramework)' == 'netcoreapp1.0'">Full</DebugType>
```
4. Save the csproj

## Expected behavior
Error message is shown. VS keeps editor open for user to modify the csproj.

## Actual behavior
Error message is shown. VS crashes. Sometimes it hangs.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Build.Exceptions.InvalidProjectFileException
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(System.String, Microsoft.Build.Shared.IElementLocation, System.String, System.Object[])
   at Microsoft.Build.Evaluation.Parser.Parse(System.String, Microsoft.Build.Evaluation.ParserOptions, Microsoft.Build.Construction.ElementLocation)
   at Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Microsoft.Build.Evaluation.ParserOptions, Microsoft.Build.Evaluation.Expander`2<System.__Canon,System.__Canon>, Microsoft.Build.Evaluation.ExpanderOptions, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.String>>, System.String, Microsoft.Build.Construction.ElementLocation, Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Framework.BuildEventContext, Microsoft.Build.Evaluation.ProjectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EvaluateConditionCollectingConditionedProperties(Microsoft.Build.Construction.ProjectElement, System.String, Microsoft.Build.Evaluation.ExpanderOptions, Microsoft.Build.Evaluation.ParserOptions, Microsoft.Build.Evaluation.ProjectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EvaluatePropertyElement(Microsoft.Build.Construction.ProjectPropertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EvaluatePropertyGroupElement(Microsoft.Build.Construction.ProjectPropertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement)
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Evaluate(Microsoft.Build.Evaluation.IEvaluatorData`4<System.__Canon,System.__Canon,System.__Canon,System.__Canon>, Microsoft.Build.Construction.ProjectRootElement, Microsoft.Build.Evaluation.ProjectLoadSettings, Int32, Microsoft.Build.Collections.PropertyDictionary`1<Microsoft.Build.Execution.ProjectPropertyInstance>, Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Evaluation.IItemFactory`2<System.__Canon,System.__Canon>, Microsoft.Build.Evaluation.IToolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache, Microsoft.Build.Framework.BuildEventContext, Microsoft.Build.Execution.ProjectInstance)
   at Microsoft.Build.Evaluation.Project.Reevaluate(Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Evaluation.ProjectLoadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(Microsoft.Build.BackEnd.Logging.ILoggingService, Microsoft.Build.Evaluation.ProjectLoadSettings)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.PrepareResourceForConcurrentAccessAsync(Microsoft.Build.Evaluation.Project, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2+Helper[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<.ctor>b__8_2(System.Threading.Tasks.Task, System.Object)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2+Helper+<GetResourceAsync>d__14[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectProperties+<GetEvaluatedPropertyValueAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageProperty+<GetValueAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty+<GetValueAsStringAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty+<GetValueAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher+<GetProjectLockFilePathAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher+<ProjectTree_ChangedAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## Environment
VS 2017, d15rel/26210.2

**Comment by 333fred** [comment] 2017-02-13 18:14
@lifengl, is this an error the `ProjectLockService` should be handling?

**Comment by lifengl** [comment] 2017-02-13 21:01
it is being discussed https://github.com/dotnet/roslyn-project-system/issues/1435#issuecomment-278839281

**Comment by 333fred** [comment] 2017-02-13 21:03
Ah, thanks. Looks like this is a dupe of that bug: https://github.com/dotnet/roslyn-project-system/issues/1435.

**Closed by 333fred** 2017-02-13 21:03 UTC
Labels: Bug
