### ISSUE TITLE
Cannot set Startup object

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1301] opened 2017-01-23 04:25 UTC
1. File -> New Console App (.NET Core)
2.  In Program.cs:

``` C#
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}

class Program2
{
    static int Main()
    {
        Console.WriteLine("Hello World!");

        return 0;
    }
}

```

3. Choose Properties -> Drop down Startup object

Expected:
![image](https://cloud.githubusercontent.com/assets/1103906/22191569/2534753c-e180-11e6-8b70-df2c7e4c3309.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/1103906/22191576/33a3bd4e-e180-11e6-9d5f-9b3f4a2db697.png)

**Comment by srivatsn** [comment] 2017-01-28 23:57
Dupe of https://github.com/dotnet/roslyn-project-system/issues/763

**Closed by srivatsn** 2017-01-28 23:57 UTC

**Comment by MeyankDwivedi** [comment] 2022-07-10 09:16
Is this Issue Resolved already? 
Because it's I think still there.

**Comment by drewnoakes** [comment] 2022-07-10 22:20
@MeyankDwivedi this issue is many years old. Please open a new issue, giving your VS version and clear repro steps so that we can investigate.
