### ISSUE TITLE
Hand-edited project file does not preserve whitespace or comments

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#779] opened 2016-11-20 08:53 UTC
If we're going to work directly on .csproj files like we did on project.json the experience needs to be better than it currently is. I can make a project file pretty readable by organising items and properties into groups, separating them, and then adding line/block comments.. but all of this is lost next time Visual Studio updates the file. It's particularly annoying to reopen the file and find that it went from this...
```
  <ItemGroup>
    <!-- Source globs -->
    <Compile Include="**\*.cs" />

    <!-- Extra files -->
    <None Include="typings\react-dom.d.ts" />
    <None Include="typings\react.d.ts" />
  </ItemGroup>
```
...to this:
```
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="typings\react-dom.d.ts" />
    <None Include="typings\react.d.ts" />
  </ItemGroup>
```

Obviously it also creates a bunch of source control churn. Can this be fixed? Something like Roslyn does, where it preserves 'trivia' in the AST, would be ideal.

**Comment by KirillOsenkov** [comment] 2016-11-20 17:54
I have a prototype XML parser that preserves white space and trivia:
https://github.com/KirillOsenkov/XmlParser

But it's going to be a lot of work to switch to that.

**Comment by 333fred** [comment] 2016-11-20 18:15
Dupe of #512 and #743.

**Closed by 333fred** 2016-11-20 18:15 UTC

**Comment by gulbanana** [comment] 2016-11-21 01:38
ah, nice to see it's in progress
