### ISSUE TITLE
WP8 projects cannot add P2P ref to cross-compiled CPS proj

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1473] opened 2017-02-05 07:02 UTC
Split out from https://github.com/dotnet/roslyn-project-system/issues/936 filed by @onovotny

@onovotny said:

In GitHub.com/onovotny/zeroconf, the dev branch, there's a ZeroconfTest.WP project that's WP8 SL. It may not have full editors, but it definitely still compiles by using the language targets.
I'm still seeing that issue with GetPackagingOutputs on it.

**Comment by davkean** [comment] 2017-02-09 22:21
@nguerrera Here's one tracking the WP8 SL projects, apparently we're missing GetPackagingOutputs.

**Comment by nguerrera** [comment] 2017-02-23 23:09
This is effectively a dupe of https://github.com/dotnet/sdk/issues/707 (PR coming soon that fixes both).

**Closed by nguerrera** 2017-02-23 23:09 UTC
Labels: Bug
