### ISSUE TITLE
ResolveComReferencesDesignTime target not found after editing project

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-project-system#881] opened 2016-12-06 07:19 UTC
VS: d15prerel 26005.5

1. Create a new .NET Core console app
1. Edit the project in the editor (while the project remains open)
1. Change TargetFramework property to TargetFrameworks (add an 's') and add `;net45` to the value.
1. Add `Condition=" '$(TargetFramework)' == 'netcoreapp1.0' " ` to the two package references.
1. Save

**Expected**
The project picks up the change immediately.

**Actual**
If you Reload the project (#880) you'll likely see errors in the error list about missing targets. I first saw one about `ResolveComReferencesDesignTime` being missing. 
But right now I see this one:

| Severity	| Code	| Description	| Project	| File	| Line	| Suppression State
| -- | -- | -- | -- | -- | -- | -- |
Error	| MSB4057	| The target "ResolvePackageDependenciesForBuild" does not exist in the project.	| ConsoleApp6	| C:\Program Files (x86)\Microsoft Visual Studio\2017\d15prerel\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	| 1871	

![image](https://cloud.githubusercontent.com/assets/3548/20916422/9ce51444-bb40-11e6-8196-2ee2e266015e.png)

**Comment by rainersigwald** [comment] 2016-12-06 18:57
If you condition out the `Microsoft.NET.Sdk` package, you're conditioning out the mechanism that (in that very-slightly-old build) provides that target.

In the latest builds, the targets will be provided by imports from the `Sdk` attribute on the project rather than a NuGet `PackageReference`, so you won't be able to create this situation.

For now, just don't condition out the `Sdk`.

**Comment by srivatsn** [comment] 2016-12-13 21:45
This should be fixed in latest builds because the SDK will always be there. Please reopen if you see this still.

**Closed by srivatsn** 2016-12-13 21:45 UTC

**Comment by davkean** [comment] 2017-02-14 04:12
This looks to be actual dupe of https://github.com/dotnet/roslyn-project-system/issues/1479#issuecomment-278771305
