### ISSUE TITLE
Migration seems to hang on some solutions

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#678] opened 2016-10-31 20:34 UTC
Repro:
Install latest bits (I used \\vspfs3\public\devops\drops\VS\d15rel\25831.00 )
Git clone https://cadddemos.visualstudio.com/BikeSharing360/Plain%20Concepts%20Team/_git/ContainersDemoNetCore
Open BikeSharing.PrivateWeb.sln

Expected results
Migration succeeds and restore, build, run is successful with no errors

Actual result
Migration hangs. 
After killing VS instance, again attempted migration. This time around no hang. But restore, build errors.

**Comment by piotrpMSFT** [comment] 2016-11-01 05:29
@morrisjoe does this repro from a command-line migration?

**Comment by morrisjoe** [comment] 2016-11-01 05:54
@jinujoseph who is attempting that.

**Comment by jinujoseph** [comment] 2016-11-01 17:24
@piotrpMSFT have not seen a hang from the command-line yet.

**Comment by piotrpMSFT** [comment] 2016-11-01 18:20
Great! if we see one, please open an issue for me in /dotnet/cli!

**Comment by 333fred** [comment] 2016-11-03 01:35
I've been unable to repro this, I've tried my machine and low power (1 core, 4 GB of RAM) vms, on d15rel 25831.01 and 25902.02. If anyone can get a dump, both of the VS instance that's running, and of the dotnet executable spawned from VS, I can investigate further.

**Comment by 333fred** [comment] 2016-11-03 01:35
If there is no dotnet executable spawned by VS, that also tells me something, so mention if there isn't one.

**Comment by srivatsn** [comment] 2016-11-09 17:21
We got a dump and it turned to be the nuget restore hang that was recently fixed.

**Comment by jinujoseph** [comment] 2016-11-10 19:38
This still repros for me in d15rel/25909.0

**Comment by 333fred** [comment] 2016-11-10 23:19
This appears to be caused by dotnet/roslyn#15143.

```
20 08d8ddc0 6dd53ce0 clr!GetCOMIPFromRCWHelper+0xb6 f:\dd\ndp\clr\src\vm\stubhelpers.cpp @ 420]
21 08d8dde8 0364750b clr!StubHelpers::GetCOMIPFromRCW+0x1e3 f:\dd\ndp\clr\src\vm\stubhelpers.cpp @ 523]
22 08d8de5c 6bc5146c Microsoft_VisualStudio_OLE_Interop!DomainNeutralILStubClass.IL_STUB_CLRtoCOM(System.Guid ByRef, System.Guid ByRef, IntPtr ByRef)+0x7b
23 08d8deb4 6bc51379 Microsoft_VisualStudio_Shell_15_0_ni!Microsoft.VisualStudio.Shell.ServiceProvider.QueryService(System.Guid, System.Type, Boolean, System.Object ByRef)+0xdc F:\dd\src\env\shell\PackageFramework\Current\Shell\ServiceProvider.cs @ 228]
24 08d8def0 6bc5197c Microsoft_VisualStudio_Shell_15_0_ni!Microsoft.VisualStudio.Shell.ServiceProvider.GetService(System.Type, Boolean)+0x69 F:\dd\src\env\shell\PackageFramework\Current\Shell\ServiceProvider.cs @ 98]
25 08d8df00 6bc730de Microsoft_VisualStudio_Shell_15_0_ni!Microsoft.VisualStudio.Shell.ServiceProvider.GetService(System.Type)+0xc F:\dd\src\env\shell\PackageFramework\Current\Shell\ServiceProvider.cs @ 84]
26 08d8df00 1ca887cb Microsoft_VisualStudio_Shell_15_0_ni!Microsoft.VisualStudio.Shell.VsServiceProviderWrapper.GetService(System.Type)+0xe F:\dd\src\env\shell\PackageFramework\Current\Shell\VsServiceProviderWrapper.cs @ 39]
27 08d8df10 6dc5ea96 Microsoft_VisualStudio_LanguageServices!Microsoft.VisualStudio.LanguageServices.Implementation.SaveEventsService..ctor(Microsoft.VisualStudio.Editor.IVsEditorAdaptersFactoryService, Microsoft.CodeAnalysis.Editor.ICommandHandlerServiceFactory, Microsoft.VisualStudio.Shell.SVsServiceProvider)+0x33 E:\A\_work\3\s\src\VisualStudio\Core\Def\Implementation\SaveEventsService.cs @ 37]
```

**Comment by 333fred** [comment] 2016-11-11 00:29
This is a dupe of internal bug 274486. @jasonmalinowski is working on https://github.com/dotnet/roslyn/pull/14354, which should resolve the threading issues that are causing this issue.

**Closed by 333fred** 2016-11-11 00:29 UTC
Labels: Bug
