### ISSUE TITLE
VS2017RC3 - Dependencies aren't grouped per target framework in Solution Explorer

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn-project-system#1464] opened 2017-02-03 06:07 UTC
Dependencies from all the target frameworks appear to be grouped together in the solution explorer. It makes figuring out dependencies for a single target framework impossible without examining the csproj file, and makes a task like searching for a package name among the transitive dependencies less useful because there is no easy way to find out which target framework it is being included with.

Given a project with target frameworks of net46 and netstandard1.0, I would like to be able to see net46 and netstandard1.0 nodes under dependencies, with their its dependencies grouped separately underneath each one.

**Comment by abpiskunov** [comment] 2017-02-03 17:22
@srivatsn @davidfowl @sayedihashimi FYI

**Comment by davkean** [comment] 2017-02-04 01:24
Yeah, thanks James, we're aware of this - still trying to come up with a design.

**Comment by srivatsn** [comment] 2017-02-08 21:12
Dupe of https://github.com/dotnet/roslyn-project-system/issues/587

**Closed by srivatsn** 2017-02-08 21:12 UTC
