### ISSUE TITLE
Version Conflict Warning on creating xUnit Test Project

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1524] opened 2017-02-09 23:50 UTC
Create xUnit Test Project (.Net Core) 
Wait for it to restore and then build 

**Expected** 
Builds successfully with out warning 

**Actual**

1>------ Build started: Project: XUnitTestProject2, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1956,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>XUnitTestProject2 -> c:\users\jinuj\documents\visual studio 2017\Projects\XUnitTestProject2\XUnitTestProject2\bin\Debug\netcoreapp1.0\XUnitTestProject2.dll
1>Done building project "XUnitTestProject2.csproj".
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

**Comment by davkean** [comment] 2017-02-09 23:54
The problem is the DependencyModel, I'm moving this bug to Test folks

```
 There was a conflict between "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
1>        "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
1>        References which depend on "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\davkean\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll].
1>            C:\Users\davkean\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll
1>              Project file item includes which caused reference "C:\Users\davkean\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll".
1>                C:\Users\davkean\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll
1>        References which depend on "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
1>            C:\Users\davkean\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170125-04\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll
1>              Project file item includes which caused reference "C:\Users\davkean\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170125-04\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll".
1>                C:\Users\davkean\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170125-04\lib\netstandard1.5\testhost.dll
1>                C:\Users\davkean\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170125-04\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1956,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```

**Comment by davkean** [comment] 2017-02-09 23:55
This issue was moved to Microsoft/vstest#465

**Closed** 2017-02-09 23:55 UTC
