### ISSUE TITLE
File context drop down doesn't stick with multi-targeting

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#1013] opened 2016-12-21 02:25 UTC
When I try to change the context of a file open in the IDE, after changing the drop down, it immediately reverts.

To repro:

- Checkout https://github.com/Reactive-Extensions/Rx.NET/tree/618817a75b466734f100b27f1ee74d5e2a54c46a
- Load Rx.NET/Source/System.Reactive.sln

Open up Observable.Queryable.cs (in ..\System.Reactive.Providers\Reactive\Linq). Now try to change the context of the file in the upper-left of the code window.

This happened with the preview2 tooling in VS 2015. My theory is that it happens with files that are outside the root level of the csproj.

**Comment by davkean** [comment] 2016-12-21 02:48
We're still not populating IsInCurrentContext - so that's probably related. Are you saying that it works for you for files inside of the project folder in above project?

**Comment by onovotny** [comment] 2016-12-21 02:52
Yes, that appears to be the case. If I add a blank file, `Class1.cs` to the root of the project, then the context for that file appears to stick.

**Comment by mavasani** [comment] 2016-12-21 03:56
Dave, we are populating IsInCurrentContext, so this is expected to work.

**Comment by mavasani** [comment] 2016-12-21 04:00
There is a known Roslyn bug due to which closing and opening any source file causes context changes to not be respected henceforth. @onovotny are you by any chance closing the file, re-opening and then trying the context switch?

**Comment by onovotny** [comment] 2016-12-21 04:05
Nope, just opening it once.

Sent from my Windows 10 phone

**Comment by davkean** [comment] 2017-01-24 08:31
@onovotny I tried this on current bits and it doesn't repro. 

I don't know what/if we fixed anything around this. Can you try in the build you installed last week and see if you can repro the same issue?

**Comment by davkean** [comment] 2017-01-24 08:36
I did find https://github.com/dotnet/roslyn-project-system/issues/1327 though, not sure what's going on there.

**Comment by onovotny** [comment] 2017-01-24 14:40
That project isn't repro'ing anymore but I have one that still does with those bits:

https://github.com/onovotny/microsoft-authentication-library-for-dotnet

Clone that and checkout the `simplify-structure` branch. With last week's build, if I open in VS, go to \src\Microsoft.Identity.Client\ then into the ..\MSAL.Common folder and open `MsalEventSource.cs`, it opens as `netstandard1.3` context. In the drop down, if I change to either the `win81` or `net45` context, it does not stick.

**Comment by davkean** [comment] 2017-01-24 22:08
Thanks, will take a look at it.

**Comment by davkean** [comment] 2017-01-25 04:31
Tried this - it's ending up in misc files in my case. Debugging.

**Comment by davkean** [comment] 2017-01-25 04:59
Okay, looks like all the configurations are failing to evaluate due to the missing targets:
```
CPS Error: 0 : Source 0 'Microsoft.VisualStudio.ProjectSystem.DataflowExtensions+SafeSourceBlockWrapper`2[Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue`1[Microsoft.VisualStudio.ProjectSystem.IProjectCapabilitiesSnapshot],Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue`1[Microsoft.VisualStudio.ProjectSystem.IProjectCapabilitiesSnapshot]]' of SyncLinkTo failed.:System.AggregateException: One or more errors occurred. ---> Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectImpl.<>c__DisplayClass90_0.<<InitializeAsync>b__3>d.MoveNext() in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\ConfiguredProjectImpl.cs:line 501
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_1.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2.Helper.<GetResourceAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.<GenerateProjectInstanceAsync>d__26.MoveNext() in E:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\ProjectSnapshotService.cs:line 207

```
We're not logging/showing this anywhere. This explains why this ends up Misc - need to figure if this is the same cause for your repro.

**Comment by onovotny** [comment] 2017-01-25 12:55
@davkean that's a start, but def not what I saw :) 

Can you install the Xamarin workload and then try again? It does seem like there should be a warning or something that tells the user what to do. Better yet, if this particular error can trigger the Xamarin workload install, that'd be great.

**Comment by davkean** [comment] 2017-02-09 01:05
Looks like the original bug is caused by #5343. Leaving this around so that I can investigate the missing targets case.

**Comment by onovotny** [comment] 2017-02-09 01:36
In still see this in RC4 btw

**Comment by davkean** [comment] 2017-02-09 01:37
Yes, it hasn't been fixed and has been pushed past RTM.

**Comment by onovotny** [comment] 2017-02-09 03:16
grr....ok

**Comment by davkean** [comment] 2017-02-09 03:27
You can add comments to the original bug. :)

**Comment by NickCraver** [comment] 2017-02-22 00:08
I'm also hitting this in MiniProfiler, seems to happen in specific #ifdrf sections and whenever a .csproj is open for editing especially. It's extremely annoying and makes the editor useless if not working in the framework it decides to default to.

How long after RTM are we looking at a fix for this? If it's Update 1, that's going to be very painful.

**Comment by NickCraver** [comment] 2017-02-22 01:46
I'm seeing this very frequently, note that the state in the bar is incorrect as well:
<img width="1048" alt="screen shot 2017-02-21 at 20 41 44" src="https://cloud.githubusercontent.com/assets/454813/23193322/4ceabcb4-f876-11e6-96b3-aa5eafd81f3f.png">
...and if I hit a letter (`d`):
<img width="1059" alt="screen shot 2017-02-21 at 20 41 53" src="https://cloud.githubusercontent.com/assets/454813/23193329/588fc2b2-f876-11e6-9971-a1001600f2ba.png">
Then the state is refreshed. Note that my screen is still grey and the IDE has changed target frameworks on me.

In a file that's entirely `#if NET46`, I keep getting kicking into netstandard. It's really quite infuriating. And it happens about once every 30-60 seconds. It makes the IDE nearly unusable. I've regressed to using VS Code to edit these files.

Please, prioritize this for a fix ASAP. It's maddeningly broken.

**Comment by NickCraver** [comment] 2017-02-22 02:17
The above state is triggered after .csproj changes under some circumstances, I'm not sure what exactly. I was simply editing references to add a package on each TFM. Once done editing, a restart of VS gets it out of this state. So there is a way to restore usability, but it's still pretty high on the annoyance factor.

**Comment by mavasani** [comment] 2017-02-22 02:44
Seems like there is more than one issue here. I'll investigate it tonight. Nick, do you have a minimal repro?

**Comment by mavasani** [comment] 2017-02-23 23:16
@NickCraver I found 2 minimal repros where the navigation bar doesn't behave correctly on opening or adding a new source file: https://github.com/dotnet/roslyn-project-system/issues/1612 and https://github.com/dotnet/roslyn-project-system/issues/1613. Additionally, we have the Roslyn issue https://github.com/dotnet/roslyn/issues/5343 where the navigation bar stops working after closing and re-opening a source file.

@srivatsn - we should target https://github.com/dotnet/roslyn-project-system/issues/1612 and project-system/issues/1613 for 15.1

@Pilchie @dpoeschl - https://github.com/dotnet/roslyn/issues/5343 has got numerous feedback requests, and we should target it for 15.1. 

Once the above issues are fixed, we can hand out the bits to the Nick and Oren for further round of testing.

**Comment by NickCraver** [comment] 2017-02-23 23:23
@mavasani Thanks (sorry missed the first ping) - the issue I'm hitting is very inconsistent but does follow making .csproj changes. I'm not sure if it's references specifically, or just an overall artifact of the roundabout .csproj edit method currently in RC4 (with a separate file). You get the "do you want to reload these changes...?" style prompt, and later follows the inconsistent framework states. 

Closing the .csproj tabs does not fix it. Restarting VS is the only fix I'm aware of, so at least there's some workaround in play. Happy to help test as always, including the advanced builds.

**Comment by mavasani** [comment] 2017-02-27 20:25
I have PRs out to fix  #1612 and #1613: https://github.com/dotnet/roslyn-project-system/pull/1637 and https://github.com/dotnet/roslyn/pull/17424 respectively. We are going to do a bar check for these issues for 15.1

@NickCraver I will try to repro the edit csproj scenario now. Please do let me know if you can repro this consistently and have concrete repro steps.

**Comment by mavasani** [comment] 2017-02-28 00:37
I have another [PR](https://github.com/dotnet/roslyn/pull/17437) out to fix the Roslyn issue https://github.com/dotnet/roslyn/issues/5343, where navigation bar switch stopped working after closing and re-opening documents. I have done a bunch of testing with these 3 PRs applied locally and navigation bar seems to work fine for me for all known cases. I will keep bashing at it to identify any more issues.

**Comment by mavasani** [comment] 2017-03-02 21:08
All the 3 PRs I mentioned above have been merged into master branch of roslyn-project-system and roslyn repos respectively.

**Closed by mavasani** 2017-03-02 21:08 UTC
Labels: Bug, RC3 Known Issue
