### ISSUE TITLE
Upgrading from .net core 1.0 to .net core 1.1 in vs2017 has extra content in solution explorer

### ISSUE THREAD

**Issue by rrelyea** [dotnet/roslyn-project-system#1047] opened 2016-12-28 00:42 UTC
Porting from: https://github.com/NuGet/Home/issues/4152
(which was based on 2 vsfeedback issues).

Procedure that leads to the bug
- Start new .Net Core console app
- Right click on project-->properties and set .NetCoreApp to 1.1 (default is 1.0)
- Save properties file and close
- Right click Dependencies Nuget-->Updates and install Microsoft.NETCore.App v1.1
- Your C: Drive should appear in Solution epxlorer down to .nuget-->(folders)-->1.4.0->runtimes-->win-->native

Looks like one of the .net core projects has 2 dlls it adds via content items via props.
those items are marked as visible false -- but they still show up in the solution explorer.

**Comment by srivatsn** [comment] 2016-12-28 20:51
Dupe of #1021

**Closed by srivatsn** 2016-12-28 20:51 UTC
