### ISSUE TITLE
Re-open ASP.NET Core project, you get : The project system has encountered an error. Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.0'

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#660] opened 2016-10-27 22:03 UTC
INSTALL STEPS
1. Run preinstall.cmd
2. Install Dev15 RC build d15rel.25827.01 (.NET Core workload)

REPRO STEPS
1. New ASP.NET Core Web Application (.NET Core) > Empty
2. Close and re-open the project in VS

ACTUAL
Sometimes you run into this

![image](https://cloud.githubusercontent.com/assets/8246794/19787199/5e7db30e-9c56-11e6-8750-42d6b78a7bd5.png)

[VsProjectFault_3c131e93-c05f-4a7d-acfa-a810d82518ac.failure.txt](https://github.com/dotnet/roslyn-project-system/files/557148/VsProjectFault_3c131e93-c05f-4a7d-acfa-a810d82518ac.failure.txt)

**Comment by mavasani** [comment] 2016-11-02 08:47
I tried it bunch of times on d15rel 25831.1 but I am unable to repro. Can you get a dump the next time you hit this?

Additionally, the attached call stack has no C#/VB CPS assemblies, so likely a core CPS issue.

**Comment by barrytang** [comment] 2016-11-03 00:07
We are consistently seeing this. Bala is trying to get a repro.

**Comment by barrytang** [comment] 2016-11-03 00:08
We are consistently seeing this. Bala is trying to get a repro.

**Comment by MattGertz** [comment] 2016-11-06 18:27
I just repro'd this in VS 25904.02 as well, on an empty template project.  Didn't see it on the core web app project I created before it.

**Comment by v-lawu** [comment] 2016-11-14 06:20
The warning also repro in create ASP.NET Core Web Application (.NET Core) > Web Application, build Dev15 RC d15rel.25909.02.

**Comment by davkean** [comment] 2016-11-16 05:49
We don't need a dump, the stack is enough for me to figure out what's going on. There's two issues here:

1) The TypeResolutionService is going down the global "design-time assembly resolution" (DTAR) path. This is never going to work for .NET Core App or .NET Standard projects as we don't register a global framework or assemblies under C:\Program Files\Reference Assemblies\Framework for these frameworks; they all come from NuGet packages. Instead, we should make sure it goes down the project DTAR path (ie via IVsDesignTimeAssemblyResolution) so that it uses the "project context" to find assemblies from the "framework". Maybe CPS doesn't implement this?

2) Once we go down project-DTAR path we're going to run into issue that VsTargetFrameworkProvider via the light-weight metadata reader (LMR) is going to go looking for mscorlib so that it can find primitives and core types. If it doesn't find it, then it throws the following:

> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.0'

For .NET Core projects, all the core types are in System.Runtime, not mscorlib. While this is also true in other frameworks, such as portable and UWP projects, there's always been an mscorlib facade alongside System.Runtime that has simply type-forwarded to System.Runtime, so we got lucky for those. We've kicked the can down the road too long here, and we should just change LMR's code (in particular VsTargetFrameworkUniverse.GetSystemAssembly()) to fall back to System.Runtime if mscorlib isn't found.

**Comment by davkean** [comment] 2016-11-17 04:59
Another repro:

1. File -> New -> Console Application
2. Right-click -> Edit ConsoleApp1.csproj
3. Remove first `<PackageReference>`
4. Save file

![image](https://cloud.githubusercontent.com/assets/1103906/20376876/bd4448ce-acde-11e6-8af9-178f6354605a.png)

**Comment by davkean** [comment] 2016-11-28 03:59
Okay, after much struggling with the debugger and optimized code - I finally figured out the cause of the first issue. CPS provides an `IVsDesignTimeResolutionService`, but it only implements it on the project root (`IVsHierarchy`). The designer is looking it up via `IVsProject.GetItemContext` and looking for `SVsDesignTimeResolutionService`.

**Comment by davkean** [comment] 2016-11-28 06:12
Okay, more info - looks like this is a CPS change, the designer (and lots of other code) look up the service via the current "item", while we can control the root, we don't have control over the individual nodes.

**Comment by davkean** [comment] 2016-11-29 05:32
Got fixes for both issues - not sure if its going to meet CPS bar, will need to check.

**Comment by davkean** [comment] 2016-11-30 05:31
I've split this bug into three items:

https://github.com/dotnet/roslyn-project-system/issues/843
https://github.com/dotnet/roslyn-project-system/issues/842
https://github.com/dotnet/roslyn-project-system/issues/844

While the first two have fixes - the 3rd one is more complicated, and requires significant changes to CPS's implementation of DTAR.

**Comment by Ponant** [comment] 2016-12-15 21:15
@davkean I had the same problem with VS 2017 RC but with v=1.1. In addition there is a [strange behavior](https://developercommunity.visualstudio.com/content/problem/7620/danger-c-drive-appears-in-solution-explorer-when-u.html) in VS when switching from 1.0 to 1.1.

**Comment by rhegner** [comment] 2016-12-28 09:20
I have the same problem with VS 2017 RC with v=1.0.
Is there a workaround for this?

**Comment by BladeWise** [comment] 2016-12-28 10:08
I am able to open such projects by deleting bin and obj folders.
You can use the attached batch (put it inside the solution folder).
[CleanUp.zip](https://github.com/dotnet/roslyn-project-system/files/675379/CleanUp.zip)

**Comment by srivatsn** [comment] 2017-01-14 07:41
Fixed by #1148

**Closed by srivatsn** 2017-01-14 07:41 UTC
Labels: Bug, Need CPS feature

**Comment by Legends** [comment] 2018-01-03 10:39
![image](https://user-images.githubusercontent.com/966368/34517311-cbf8c36e-f07a-11e7-9d0a-3d1d1b6859d5.png)


=====================
03.01.2018 11:23:57
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.1'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.1'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()<---

===================
