### ISSUE TITLE
Error when going to the properties of a folder in VS 2017 RC4 and a ASP.NET Core project

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/roslyn-project-system#1579] opened 2017-02-16 20:59 UTC
Discussed offline with @morrisjoe 
VS 2017 RC4 and ASP.NET Core project
Randomly, when going to the properties of a folder with pictures in my project, it throws an error, as attached.
Other times it works and after accepting the error it also goes to the properties window
![error_folder_properties_vs_2017](https://cloud.githubusercontent.com/assets/1712635/23040836/9d955620-f447-11e6-9f50-842c6975229a.PNG)
.

**Comment by CESARDELATORRE** [comment] 2017-02-16 21:26
Related to that bug, I couldn't set the Pics folder to be included/copied to the Publish folder, so I had to edit the .CSPROJ file manually and add it with:
    <None Update="Pics">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
Other than that, I could not find a way to do it with VS 2017 RC4 because of the errors being thrown..

**Comment by davkean** [comment] 2017-02-16 22:37
@CESARDELATORRE That Update is likely the cause, and it doesn't do what you expect it to do. Folders don't really exist as "items" in the tree other than via `<Folder Include="Pics" />, due the above Update we think you have a file called "Pics" in your project.

We'll take a look and see if we can make this behavior better. In the mean time what you really want is this:

``` XML
  <ItemGroup>
    <None Update="Pics\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
```

You typically want `PreseveNewest`, to avoid always building project even when nothing has changed.

I've filed https://github.com/dotnet/roslyn-project-system/issues/1582 to track your scenario of what you are trying to achieve, I'll leave this bug for the behavior that you encountered.

**Comment by CESARDELATORRE** [comment] 2017-02-16 22:58
David,
Note that the crash was happening BEFORE I changed anything in the .CSPROJ file.
I had to change that, other than that dotnet publish was not copying the images to the Picts folder…

I’ll try that change in the .CSPROJ, though. Thanks! 😊
Cesar.

**Comment by davkean** [comment] 2017-02-16 23:00
You see that dialog before you _added_ the Update?

**Comment by CESARDELATORRE** [comment] 2017-02-16 23:05
Yep. 100% for sure. That error was appearing BEFORE I updated the .CSPROJ manually.

**Comment by davkean** [comment] 2017-02-16 23:06
Can you share out a project?

**Comment by CESARDELATORRE** [comment] 2017-02-16 23:09
Sure. But it is a private GitHub repo.
Send me your GitHub account so you can clone it, ok?

Cesar.

**Comment by davkean** [comment] 2017-02-16 23:24
Commit  dc1a245.

**Comment by CESARDELATORRE** [comment] 2017-02-17 00:34
I ant to highlight that these errors were appearing BEFORE I changed anything manually in the .CSPROJ file.
Also, when clicking on menu options of the folder, like below:
![error_folder_properties_vs_2017_2](https://cloud.githubusercontent.com/assets/1712635/23047614/ca727d8a-f465-11e6-8665-75eadb2287f0.PNG)

**Comment by davkean** [comment] 2017-03-20 02:26
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=397481&fullScreen=false&_a=edit.

**Closed by davkean** 2017-03-20 02:26 UTC

**Comment by viktorveis** [comment] 2017-05-26 01:04
We couldn't reproduce this issue on the latest build. Please let us know if you still experience it.
