### ISSUE TITLE
Improve error pane navigation for duplicate package errors.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1205] opened 2017-01-17 00:08 UTC
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/tree/5f2b81f0edf1ada009806a852a0749081980ac85
2. Open `Dapper.sln` in VS 2017 RC
3. Open the error window

User is presented with a duplicate reference warning, like this:
<img width="1162" alt="screen shot 2017-01-16 at 18 50 44" src="https://cloud.githubusercontent.com/assets/454813/22003038/9da3e23a-dc1e-11e6-93a5-75628d6bc053.png">

Currently, this navigates to `Microsoft.NET.Sdk.DefaultItems.targets`, like this:
<img width="1158" alt="screen shot 2017-01-16 at 18 55 07" src="https://cloud.githubusercontent.com/assets/454813/22003083/f0d2c098-dc1e-11e6-95bf-b1ad39152660.png">

Instead, this should navigate to the `.csproj` with the issue, so the user can actually take the action of fixing this line:
```xml
<PackageReference Include="Microsoft.NETCore.App" Version="1.0.3" />
```

**Comment by srivatsn** [comment] 2017-01-18 19:09
Dupe of https://github.com/dotnet/sdk/issues/654

**Closed by srivatsn** 2017-01-18 19:09 UTC
