### ISSUE TITLE
Cannot use the Visual Studio Performance Profiler in some solutions

### ISSUE THREAD

**Issue by Yves57** [dotnet/roslyn-project-system#996] opened 2016-12-19 14:51 UTC
I'm not sure that it is right place to declare this issue...

When I want to to use the Visual Studio 2017 RC Profiler with some solutions, I cannot select the executable I want.
If I create a new .NET Core Console App, everything is OK.
But for instance when I want to profile the RazorPageGenerator (ASP.NET Core Razor repository), the project is not selectable.
![image](https://cloud.githubusercontent.com/assets/11701094/21316802/b6a92704-c602-11e6-9e0f-f2e9a83e6dc3.png)

I dont' understand the difference... For information, I almost sure that I already had the problem before with Visual Studio 2015 and at least .NET Core solutions.

**Comment by 333fred** [comment] 2017-02-03 21:20
Dupe of internal bug [238474](https://devdiv.visualstudio.com/DevDiv/_workitems?id=238474&_a=edit). The profiler team is aware of this, but won't be able to get to it for RTM.

**Closed by 333fred** 2017-02-03 21:20 UTC
Labels: Bug, Urgency-Soon

**Comment by omerlh** [comment] 2018-12-09 09:30
Any update about this issue? The link is to an internal system which I cannot access

**Comment by davkean** [comment] 2018-12-09 09:54
@omerlh It looks like this internal bug is tracking a slightly different issue. Can you Help -> Send Feedback -> Report a Problem and point me to it and I can route to the right team.

**Comment by omerlh** [comment] 2018-12-09 10:19
Sure, feedback on visual studio?
