### ISSUE TITLE
File reload prompt appears if .csproj file is open and you make a change to the project file

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1014] opened 2016-12-21 04:05 UTC
- File \ New Project \ Console App (.NET Core)
- Right click on project, select "Edit .csproj"
- Right click on "Program.cs", select "Exclude from project"

EXPECTED: `.csproj` file is reloaded in editor
ACTUAL: Prompt asking you if you want to reload the project file:

![image](https://cloud.githubusercontent.com/assets/145043/21377059/727cf464-c6ef-11e6-8b61-3d20bd467fd3.png)

The prompt doesn't show if you've enabled "Reload modified files unless there are unsaved changes", so perhaps this is the expected behavior.  However, it feels a bit weird that the project is supposed to transparently reload (though it [currently isn't](#880)), but that if you're viewing the .csproj file itself, it doesn't behave the same way.

**Comment by srivatsn** [comment] 2016-12-21 18:09
With the approach that we are using currently this is by design. Fred's trying to move to an in-memory model which will get rid of this issue but ofcourse that approach comes with a different set of issues. Using this issue to track the in-memory approach.

**Comment by 333fred** [comment] 2016-12-22 01:27
Closing this in favor of #780.

**Closed by 333fred** 2016-12-22 01:27 UTC
Labels: Feature Request
