### ISSUE TITLE
VS 2017 RC - 2 "General" tabs in publish profile Properties page

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1330] opened 2017-01-24 19:26 UTC
_From @scottaddie on January 17, 2017 22:14_

Create a new ASP.NET Core 1.1 Web Application targeting .NET Core using the project template. Right-click the project in Solution Explorer, and create a new publish profile using the **Folder** publish target. Right-click the resulting .pubxml file, and select **Properties**. Notice that the **Configuration Properties/General** tab appears twice:

![general_tab](https://cloud.githubusercontent.com/assets/10702007/22042152/ccfb9fa0-dcbe-11e6-9c96-39b324c84ecd.png)

It's also interesting that the content of each of the 2 **General** tabs is slightly different. Here's tab 1:
![general_tab_1](https://cloud.githubusercontent.com/assets/10702007/22042242/224b665c-dcbf-11e6-8fc9-e83f4e59a93b.png)

Here's tab 2:
![general_tab_2](https://cloud.githubusercontent.com/assets/10702007/22042237/1d7bc02c-dcbf-11e6-867c-84a6bbe988b4.png)

_Copied from original issue: aspnet/Tooling#952_

**Comment by srivatsn** [comment] 2017-01-24 19:26
_From @mlorbetske on January 17, 2017 23:29_

TFS Bug#369161

**Comment by srivatsn** [comment] 2017-01-24 19:26
_From @mlorbetske on January 18, 2017 0:7_

@BillHiebert any idea what would cause this?

**Comment by srivatsn** [comment] 2017-01-24 19:26
_From @scottaddie on January 18, 2017 6:36_

I also see 2 **General** tabs in the Properties page of the following file in the aspnet/Scaffolding repo: `src\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\Templates\ViewGenerator\Edit.cshtml`

**Comment by srivatsn** [comment] 2017-01-24 19:28
@morlebtske says "This seems to repro even for text files in all .NET Core project types"

**Comment by davkean** [comment] 2017-01-24 22:42
Dupe of https://github.com/dotnet/roslyn-project-system/issues/397

**Comment by davkean** [comment] 2017-01-24 22:42
Make note that this bug and #397 have different milestones.

**Closed by davkean** 2017-01-24 22:42 UTC
Labels: Bug
