### ISSUE TITLE
Root level packages show up as "DynamicTypeBrowseObject" in the object browser

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1257] opened 2017-01-19 10:24 UTC
![image](https://cloud.githubusercontent.com/assets/1103906/22103002/92d7c4fe-de8d-11e6-9bff-068ed35c3117.png)

Usually these have friendly names, such as Package or Dependency. If you choose the child, you get:

![image](https://cloud.githubusercontent.com/assets/1103906/22103035/a99e3ccc-de8d-11e6-8f57-459a2009cd84.png)

**Comment by srivatsn** [comment] 2017-01-30 17:23
Dupe of https://github.com/dotnet/roslyn-project-system/issues/1258

**Closed by srivatsn** 2017-01-30 17:23 UTC
