### ISSUE TITLE
Get an error when you attempt to choose a strong name key

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1306] opened 2017-01-23 04:49 UTC
1. File -> New Class Library (.NET Standard)
2. Choose **Properties** -> **Signing** 
3. Check **Sign the assembly**
4. Under "choose a strong name key file", drop the drop down

```
---------------------------
Microsoft Visual Studio
---------------------------
AssemblyOriginatorKeyFile:

Value cannot be null.

Parameter name: value
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment] 2017-01-23 04:52
After you get this in state, you can't get out of it or close Visual Studio. It continues to display the error.

**Comment by mavasani** [comment] 2017-01-23 06:23
Dupe of VSO 364884

**Comment by mavasani** [comment] 2017-01-23 06:24
https://devdiv.visualstudio.com/DevDiv/_workitems?id=364884&_a=edit

**Closed by mavasani** 2017-01-23 06:24 UTC
