### ISSUE TITLE
Turning on Diagnostic logging in VS increased build time by a lot

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-project-system#1576] opened 2017-02-16 04:00 UTC
**Repro**:
1. Create a new Class Library (.NET Core) project
2. Navigate to `Tools->Options->Projects and Solutions->Build and Run`
3. Change the `MSBuild project build output verbosity` to `Detailed` (`Minimal` is the default)
4. Exit the dialog
5. Build the solution and track the time it takes for the output window to display `========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========` (this, for me is consistently sub 1 second)
6. Rebuild the solution and see that the build time stays consistent with that in step 5
7. Navigate back to `Tools->Options->Projects and Solutions->Build and Run`
8. Change the `MSBuild project build output verbosity` to `Diagnostic` (optionally validate that the other option levels don't repro this issue)
9. Exit the dialog
10. Build the solution and track the time it takes for the output window to display `========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========`

**Expected behavior**:
The total time taken for a Diagnostic build should be near to the total time for a Details build.

**Actual behavior**:
The total time taken for a Diagnostic build is greater than 10 seconds on my machine, although MSBuild reports the build (including logging) took less than 1 second.

VS additionally appears to freeze/lock at multiple points during the build.

This time it takes to complete a build continues increasing with the number of projects. A small solution with only 10 projects was taking well over 2 minutes to complete.

**Comment by davkean** [comment] 2017-02-16 04:37
Yep, dupe of https://github.com/dotnet/roslyn-project-system/issues/1242. Should be fixed soon.

**Closed by davkean** 2017-02-16 04:37 UTC
