### ISSUE TITLE
Unable to change project properties via the AppDesigner

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#841] opened 2016-11-30 03:34 UTC
1. Create new .NET Core applicaton
2. Change Assembly Name
3. Tab to the next control

Expected: Assembly name to remain the same
Actual: Assembly reverts to its previous value

**Comment by davkean** [comment] 2016-11-30 03:36
I quickly debugged this - this is an issue in PropertyDescriptionSetValueHelper.SetValue, the _valueChangedWasFired isn't being set to true, so we think the project was about to be checked out from source control, and the user cancelled it. This looks very much like the issue we had in CPS a couple of months ago. //cc @srivatsn

**Comment by davkean** [comment] 2016-11-30 06:49
Walked through this – this looks like this was caused by Jinu’s change to hide properties from the Properties window. This caused a different descriptor “HiddenPropertyDescriptor” to be returned instead of the DynamicPropertyDescriptor which meant that the events where no longer being fired.

**Comment by RaulPerez1** [comment] 2016-11-30 23:20
#857 is most likely a dupe of this.

**Closed** 2016-12-06 19:56 UTC
Labels: Bug
