### ISSUE TITLE
Edit Pre-build event crashes Visual Studio 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#819] opened 2016-11-28 00:46 UTC
1. File -> New Console Application (.NET Core App)
2. Properties -> Build Events -> Edit Pre-Build event

--Crash--

```
Exception Info: System.InvalidCastException
   at Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValue(System.String)
   at Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValues(System.String[] ByRef, GetTokenValueFunc)
   at Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.LaunchEventBuilder(Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage, GetTokenValueFunc, System.String, System.String ByRef)
   at Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.PreBuildBuilderButton_Click(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnClick(System.EventArgs)
   at System.Windows.Forms.Button.OnClick(System.EventArgs)
   at System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ButtonBase.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Button.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by davkean** [comment] 2016-11-28 00:47
May be related to: https://github.com/dotnet/roslyn-project-system/issues/814

**Comment by jinujoseph** [comment] 2016-11-28 02:00
dupe of #405 ?

**Comment by davkean** [comment] 2016-11-28 02:01
This one looks different to that one, the stack is different.

**Comment by RaulPerez1** [comment] 2016-11-30 00:08
It is a dupe of #405, the root cause is that the CPS hierarchy does not implement IVsBuildMacro which used to be implemented in the old project system

**Closed by RaulPerez1** 2016-11-30 00:08 UTC
Labels: Bug
