### ISSUE TITLE
Dynamically generated TFMs not displayed in VS

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#1624] opened 2017-02-25 19:23 UTC
I have a [.NET Core csproj](https://github.com/wjk/CentennialChromium/blob/master/MSBuild.ResGen/MSBuild.ResGen.csproj) containing the following code:

```xml
<PropertyGroup>
  <TargetFrameworks>netcoreapp1.1</TargetFrameworks>
  <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net46; netcoreapp1.1</TargetFrameworks>
</PropertyGroup>
```

The reason for the conditional on the `TargetFrameworks` property is so that I can build the project for full-framework on Windows, yet still build it successfully using `dotnet build` on non-Windows platforms, where I cannot (easily) restore for `net46`. (I need to dual-target .NET Core and .NET Framework because this project contains MSBuild tasks, and I cannot easily get VS MSBuild to load a .NET Standard task assembly.)

This project restores and builds in VS quite well. (It doesn't work when loaded into MSBuild, though, due to an erroneously added dependency on `System.Xml.Linq.dll`, but that's a separate issue.) The issue I am reporting here is that when I open a code file in this project, I cannot switch the editor to display `net46` references using the scope bar. Apparently the scope bar is not smart enough to detect conditionally applied changes to the `TargetFrameworks` property like I have done above.

**Comment by mavasani** [comment] 2017-02-25 22:02
Dupe of https://github.com/dotnet/roslyn-project-system/issues/547. @RaulPerez1 does your new configuration approach address this?

**Comment by RaulPerez1** [comment] 2017-02-27 20:53
No but I think I know what the problem is and that's currently by design. If TargetFramework is specified that provider will give precedence over the TargetFrameworks property.

This should work I believe:
<TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net46; netcoreapp1.1</TargetFrameworks>
<TargetFrameworks Condition="'$(OS)' != 'Windows_NT'">netcoreapp1.1</TargetFrameworks>

**Comment by srivatsn** [comment] 2017-03-01 21:52
In this case though TargetFramework is not defined. If TargetFramework is defined then yes it gets precedence over TargetFrameworks because the semantics of TargetFrameworks is that it launches a new msbuild for each TF defined by setting TargetFramework to that value. Closing as dupe of #547.

**Closed by srivatsn** 2017-03-01 21:52 UTC
