### ISSUE TITLE
Adding multiple files when project has multiple TFMs confuses project system

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/roslyn-project-system#1735] opened 2017-03-13 16:08 UTC
When I add multiple class files to a project that has targets multiple frameworks, then the project system gets confused and fails to provide corrent intellisense information.

When you try to continue working, then it gets even worse and sometimes a build fails even though everything is fine. You then have to restart VS 2017 to be able to build the project.

# Steps to reproduce

1. Create a .NET Standard class library project
2. Change `<TargetFramework>netstandard1.4</TargetFramework>` to `<TargetFrameworks>net451;netstandard1.4</TargetFrameworks>`
3. Add three more class files

# Expected

The new `Class4` should be usable and the drop down list in the upper left corner of the text editor shows `ClassLibrary1(net451)`.

# Actual

* The drop down list in the upper left corner of the text editor for `Class4` shows `Sonstige Dateien` (problably `Other Files` in english).
* In `Class1`, Intellisense doesn't show `Class4`
* In `Class1`, Intellisense shows that `Class3` isn't available for `netstandard1.4`

# Workaround

Sometimes, an un- and reload of the project works, but sometimes the whole solution needs to be closed and loaded again.

**Comment by davkean** [comment] 2017-03-14 03:36
@mavasani This spells like the recent issue that you fixed, right?

**Comment by davkean** [comment] 2017-03-16 23:48
This is a dupe of https://github.com/dotnet/roslyn-project-system/issues/1612.

**Closed** 2017-03-17 00:48 UTC
