### ISSUE TITLE
Missing SDK Element crashes Visual Studio

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1012] opened 2016-12-21 01:15 UTC
1. Create a new .NET Core Console App.
2. Open the csproj and remove the SDK attribute. (Internal editor or external, doesn't matter).
3. Project will reload.

Expected:
Reloads in some degraded state. Maybe it says failed to load with some reason.

Actual:
![image](https://cloud.githubusercontent.com/assets/2371880/21373920/5e3020c0-c6d7-11e6-97e3-fd443ac68232.png)

Attempting to open a solution with a missing SDK element will also result in VS stopping. Tested on d15prerel/21609.05

**Comment by davkean** [comment] 2016-12-21 05:36
Updated title to better describe the issue.

**Comment by srivatsn** [comment] 2016-12-21 18:02
Dupe of https://github.com/dotnet/roslyn-project-system/issues/793. Looks like the experience has degraded further from showing some weird dialogs to VS crashing. Let's use #793 to track this.

**Closed by srivatsn** 2016-12-21 18:02 UTC
