### ISSUE TITLE
 Resource.resx generated code doesn't compile for .netstandard library

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#1117] opened 2017-01-09 22:21 UTC
Ported from https://github.com/aspnet/Tooling/issues/936 by @MarkPflug

Steps to reproduce:
Create a new project, Class Library (.NET Standard)
Add a new Resources File to the project (Resource1.resx)
Compile.

Expected:
Successful compilation

Actual:
Compiler error: 'Type' does not contain a definition for 'Assembly' and no extension ...

The code generated in Resource1.Designer.cs contains the offending line:

`global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary1.Resource1", typeof(Resource1).Assembly);`

Version (latest as of 2017-01-09):
Microsoft Visual Studio Professional 2017 RC
Version 15.0.26020.0 D15REL

**Comment by srivatsn** [comment] 2017-01-11 02:48
Dupe of #747

**Closed by srivatsn** 2017-01-11 02:48 UTC
