### ISSUE TITLE
Adding a file to a cross targeted project only adds it to a single context

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#1533] opened 2017-02-11 05:38 UTC
I'm working in the ASP.NET repositories which has mostly converted to the new csproj. Libraries usually target net451 and netstandard1.3. Whenever I add a file to one of these projects it only ever seems to exist in a single context (I believe the first one declared in the file). If I add the file on disk it appears in both, if I close and re-open the solution it appears in both.

**Comment by davkean** [comment] 2017-02-11 05:54
@mavasani @lifengl Maybe CPS isn't triggering evaluation on all configurations when the watcher fires? Not in front a computer, but @davidfowl if you Edit project via editor and just save it with zero changes, does that cause it to appear in other contexts?

**Comment by davidfowl** [comment] 2017-02-11 08:04
That works.

**Comment by lifengl** [comment] 2017-02-11 18:56
We have two pieces of logic here:

Each configuration is watching the project model to be touched, and refreshing itself.  This is normally how it works.  But in a file globbing case, this logic won't work, because the msbuild is not changed.

Second logic is that each configuration is all watching directory changes and decides whether it touches globbing.  In this case, we expect this to work.

Based on the thread, if the file is added to the disk, it works (David, can you confirm?)

If that is case, maybe some optimization code to prevent extra checks in the second logic when the item is added through the project system might be broken.

Sent from my phone

On Feb 11, 2017, at 12:04 AM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


That works.

**Comment by davidfowl** [comment] 2017-02-19 07:00
> Based on the thread, if the file is added to the disk, it works (David, can you confirm?)

Yes it works.

**Comment by davkean** [comment] 2017-02-28 13:51
This looks like https://github.com/dotnet/roslyn-project-system/issues/1612.

**Comment by mavasani** [comment] 2017-02-28 16:04
Yes, this is a dupe of #1612

**Closed** 2017-02-28 16:04 UTC
Labels: Resolution - Duplicate
