### ISSUE TITLE
Certain projects fail to load second time around

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1133] opened 2017-01-11 02:29 UTC
1. Create a new Empty Web Application (.NET Core)
2. Add a new Console Application (.NET Core)
3. Add a new Console Application (.NET Core)
4. File -> Close Solution
5. Reopen Solution

Expected: all projects load
Actual: Web project fails to load

![image](https://cloud.githubusercontent.com/assets/1103906/21832826/f4d780a0-d801-11e6-93d2-869b02f6bf15.png)

**Comment by davkean** [comment] 2017-01-11 02:33
I suspect this is caused by https://github.com/dotnet/roslyn-project-system/issues/1103, but can't confirm - attaching a debugger loses the repro.

Make note, CPS is supposed to enter a faulted project tree in this case, but isn't - @adrianvmsft did mention today that this was broken?

**Comment by adrianvmsft** [comment] 2017-01-11 18:23
The fault tree issue was different - it was randomly generating an exception with "System.ArgumentException: The given trees are not related." and leaving the project in a "loading" state.
In the screenshot above, the load failed message is displayed correctly.
However, it is surprising that the load failed icon has the blue alert. It seems it is not a CPS project because the CPS fault tree doesn't display the blue alert icon currently.

**Comment by 333fred** [comment] 2017-01-13 00:59
This is the same root cause as internal bug [286893](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=286893&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&src=alerts&src-action=cta&fullScreen=true&_a=edit). However, this symptom only seems to occur when the web application is the first project added to a solution. Here are the repro steps I've been able to come up with:

1. Create an ASP.NET Core Project.
2. Add any other type of project to the solution (except another asp.net project. I've tested multiple types of Console Apps/Class Libraries, doesn't have to be .NET Core).
3. Close the solution
4. Reopen the solution. Load fails.

If I close the Connected Services page before closing the solution, the reload works fine. Tagging @AArnott.

**Comment by 333fred** [comment] 2017-01-13 01:03
The other workaround is simply reloading the web project after it says "load failed".

**Comment by AArnott** [comment] 2017-01-13 04:30
Bug 286893 has been fixed. Please see that bug for resolved branch and build details so you can verify it fixes your issue.

**Comment by 333fred** [comment] 2017-01-13 19:03
Tested with d15prerel/26112.08, and the issue is gone. Thanks @AArnott.

**Closed by 333fred** 2017-01-13 19:03 UTC
Labels: Bug, External
