### ISSUE TITLE
Migrated project Hangs VS 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#679] opened 2016-10-31 20:58 UTC
**Repo Step**
- You can clone this public repo from GitHub now : https://github.com/balaTest/ProjectKTestProjects.git
- Open solution under Dev14_K101/Tooling202/o	ConsoleAppOnCore_1 
- Go through the migration process 

**Expected**
project migrated successfully , you can build and run the application

**Actual**

![image](https://cloud.githubusercontent.com/assets/12449387/19871432/1e689efe-9f72-11e6-842a-5df84792a837.png)

**Comment by jinujoseph** [comment] 2016-10-31 20:59
Please note that this is flaky and doesn't reproduce all the time.

**Comment by 333fred** [comment] 2016-10-31 21:01
Dupe of #678

**Closed by 333fred** 2016-10-31 21:01 UTC
Labels: Bug
