### ISSUE TITLE
Changing TargetFramework TargetFrameworks causes project error

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1137] opened 2017-01-11 18:00 UTC
1. New dotnet core console project
2. r-click edit project file
3. Change TargetFramework to TargetFrameworks
4. Save

Get the following error.
```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.0'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.

A diagnostic log has been written to the following location: "C:\Users\billhie\AppData\Local\Temp\VsProjectFault_6e2b5b1e-8855-4ddb-a787-b308fad4ffca.failure.txt".
---------------------------
OK   
---------------------------

```

**Comment by 333fred** [comment] 2017-01-11 18:21
This is related to the DTAR stuff. @davkean is working on a PR now.

**Comment by srivatsn** [comment] 2017-01-11 19:32
Dupe of #660?

**Comment by 333fred** [comment] 2017-01-11 19:36
I'd guess it's the same issue, but a different repro.

**Comment by davkean** [comment] 2017-01-11 22:48
Dupe of #660

**Closed by davkean** 2017-01-11 22:48 UTC
Labels: Bug
