### ISSUE TITLE
After doing a solution build the status bar says Ready but continues to build

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1219] opened 2017-01-17 20:00 UTC
Following a migrate I right-clicked on a solution in order to perform a full build.  Almost immediately, VS showed ready in the status bar but the build seemingly did not continue.  Here is the dump that @srivatsn created: https://www.dropbox.com/s/2m89jiqudv65x4p/devenv.dmp?dl=1

/cc @srivatsn @morrisjoe

**Comment by srivatsn** [comment] 2017-01-18 18:56
Dupe of https://github.com/dotnet/roslyn-project-system/issues/1222

**Closed by srivatsn** 2017-01-18 18:56 UTC
