### ISSUE TITLE
Migration fails with internal error 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1488] opened 2017-02-08 00:56 UTC
Copy project from \\mlangfs1\public\Jinuj\IPA\ConsoleAppNoSln
copy over to say C:\test\ConsoleAppNoSln 
double click C:\test\ConsoleAppNoSln\ConsoleApp1.xproj 
Click on one way upgrade UI 

**Expected**

migrates successfuly 

**Actual** 
![image](https://cloud.githubusercontent.com/assets/12449387/22718593/24066bfc-ed56-11e6-8414-319e587b9619.png)

related to https://github.com/dotnet/cli/issues/5612 (cli does work when done from a subfolder)

**Comment by 333fred** [comment] 2017-02-08 18:31
This is a dupe of https://github.com/dotnet/roslyn-project-system/issues/1399, and not actually related to https://github.com/dotnet/cli/issues/5612. This was rejected from RTM, and the fix is checked into post-dev15.

**Closed by 333fred** 2017-02-08 18:31 UTC
