### ISSUE TITLE
"SDKs" show up as packages when they are indirect

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1414] opened 2017-02-01 07:04 UTC
I think this SDK thing is a leaky abstraction, for example, .NETStandard.Library shows up as SDK when it top level, but when it's a indirect, it shows up a package:

![image](https://cloud.githubusercontent.com/assets/1103906/22497905/e88956d6-e8a8-11e6-9528-21f9665c503a.png)

**Comment by abpiskunov** [comment] 2017-02-01 17:40
i think everything is as expected. in your screenshot we have an SDK X and it's dependencies, which include an SDK Y. It might have a different icon though when displayed as dependency.

**Comment by abpiskunov** [comment] 2017-02-01 17:41
Btw, i just added <PackageReference Include="NETStandard.Library" Version="1.6.0" /> to my project and it is not marked as implicit at all , and is resolved as package - what did you mean "it is SDK when it is top level"?

**Comment by abpiskunov** [comment] 2017-02-01 17:42
`<PackageReference` Include="NETStandard.Library" Version="1.6.0" />

**Comment by davkean** [comment] 2017-02-01 21:21
That's my point how we marked SDK'd as SDKs is leaky - it only works if all of them are marked implicit, here .NETStandard.LIbrary is pulled it because of it's referenced by a implicit package.

**Comment by fubar-coder** [comment] 2017-02-08 10:16
@abpiskunov When you use a console app, it shows up as child of "Microsoft.NETCore.App". But when you use a class library, it shows up directly under "SDK", thus it shows up at top level.

**Comment by abpiskunov** [comment] 2017-02-08 17:24
dupe of RTM approved issue https://github.com/dotnet/roslyn-project-system/issues/1456 , we will be hiding all default implicit packages and show them as SDK only

**Closed by abpiskunov** 2017-02-08 17:24 UTC
Labels: Bug
