### ISSUE TITLE
No Ctrl+. light bulb support when trying to add Mvc service in Startup.cs

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#583] opened 2016-10-10 23:01 UTC
**INSTALL STEPS**
1. Install WPT.25810.00
2. Add private MyGet feeds in Package Manager Settings dialog
 
**REPRO STEPS**
1. File > New > ASP.NET Core Web Application (.NET Core) > Empty
2. Close VS. Change version of Microsoft.NetCore.Sdk.Web to 1.0.0-alpha-20161007-5 -- this is to workaround the bug where the package is not in sync with .NET Core package (TFS#275088).
3. Re-open project using VS
4. Restore Nuget packages from Solution Explorer
5. open Startup.cs
6. Type the following code in ConfigureServices method
`services.AddMvc()`

**EXPECTED**
Be able to Ctrl+. and get a suggestion to add Microsoft.AspNetCore.Mvc package

![image](https://cloud.githubusercontent.com/assets/8246794/19253795/a434be3a-8f02-11e6-94d0-fbf3c1ca143d.png)

**ACTUAL**
Ctrl+. is not available for this line
![image](https://cloud.githubusercontent.com/assets/8246794/19253813/c1eec8a8-8f02-11e6-85d4-62797bb33e83.png)

**Comment by srivatsn** [comment] 2016-10-21 07:24
This is currently behind an option in Tools->Options that's off by default. There's work underway in Roslyn to make this on by default.

**Comment by CyrusNajmabadi** [comment] 2016-10-27 22:12
I believe the issue here may be htat @balachir wants to invoke this on an unbound extension method.  That's not something we currently support in the new add-package feature.  We only support offering this on unbound non-nested types.

**Comment by CyrusNajmabadi** [comment] 2016-10-27 22:27
Dupe of https://github.com/dotnet/roslyn/issues/8757

**Closed by CyrusNajmabadi** 2016-10-27 22:27 UTC
