### ISSUE TITLE
Editing one Console App project leads to errors in subsequent projects in that session

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn-project-system#883] opened 2016-12-06 20:50 UTC
After applying the changes in #835 , the following repro steps lead to errors:

1.	Create new .NET Core App ConsoleApp1.csproj
2.	Edit the CSPROJ
3.	Close the Solution
4.	Create new .NET Core App ConsoleApp2.csproj
5.	Right-Click Project -> Manage NuGet Packages and add NewtonSoft.Json
6.	Observe the following errors. Note the reference to ConsoleApp1.csproj

- Could not find a part of the path 'C:\Users\nayewah\AppData\Local\Temp\tmp705.tmp\ConsoleApp1.csproj'.
- Package Newtonsoft.Json 3.5.8 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 3.5.8 supports:  - net20 (.NETFramework,Version=v2.0)  - net35 (.NETFramework,Version=v3.5)  - sl (Silverlight,Version=v0.0)

Workaround:
Close editor after editing CSProj

**Comment by 333fred** [comment] 2016-12-06 20:56
This only occurs when the solution is closed without closing the csproj editor first. The cause is that during solution close, https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/IMsBuildAccessor.cs#L67 attempts to get the current active configured project. However, because the solution is closing, there isn't an active configured project. This causes an exception and the msbuild listener isn't unsubscribed.

**Closed** 2017-01-06 18:57 UTC
Labels: Bug, Feature - Project File Editing
