### ISSUE TITLE
Changing from .NET Core -> 1.0 -> 1.1 -> 1.0 causes packages to disappear

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1159] opened 2017-01-13 08:15 UTC
1. Create a new .NET Core Console Application
2. Right-click project -> Properties
3. In Target framework, change .NETCoreApp 1.0 -> .NETCoreApp 1.1 
4. Wait for restore to finish
5. In Target framework, chagne .NETCoreApp 1.1 -> .NETCoreApp 1.0
6. Wait for restore to finish

Expected: For .NET Core 1.0 to be listed under dependencies node
Actual: It's empty

![image](https://cloud.githubusercontent.com/assets/1103906/21922815/9dc689b8-d9c4-11e6-8d3b-7035c214ec3f.png)

**Comment by davkean** [comment] 2017-01-13 08:43
The assets file still exists in this case, so maybe a design-time issue?

**Comment by davkean** [comment] 2017-01-13 10:13
This looks similar to: https://github.com/dotnet/roslyn-project-system/issues/784

**Comment by srivatsn** [comment] 2017-01-31 19:57
Probably a dupe of the TF change issues you are looking at.

**Comment by mavasani** [comment] 2017-02-02 09:12
@davkean I am unable to repro this anymore. I always see a NuGet dependency Microsoft.NETCore.App (1.1.0) for both netcoreapp1.0 and netcoreapp1.1 TF values.

![image](https://cloud.githubusercontent.com/assets/10605811/22543222/8b0d12f4-e8e4-11e6-8f4e-b27fb809b5b5.png)

**Comment by mavasani** [comment] 2017-02-02 09:16
If I switch between netcoreapp1.0 and netstandard1.4 and then back to netcoreapp1.0, I do see the correct NuGet dependency for both the switches. Please re-open this issue if you can still repro it on latest bits.

**Closed by mavasani** 2017-02-02 09:16 UTC
Labels: Blocking-Release, Bug, RC3 Known Issue, Urgency-Soon

**Comment by davkean** [comment] 2017-02-02 09:20
@mavasani That build that you are testing with isn't current - you don't have SDK.

**Comment by mavasani** [comment] 2017-02-02 13:00
I moved to today's build and see the same behavior. In all the above steps, the NuGet SDK reference is to Microsoft.NETCoreApp 1.1

![image](https://cloud.githubusercontent.com/assets/10605811/22550330/5ee5a900-e904-11e6-9457-019b57bca85c.png)

**Comment by davkean** [comment] 2017-02-02 22:17
Yeah, I played around with a lot last night, and am convinced it's not present anymore.
